FROM nginx:1.10

ARG NGINX_PUBLIC_DIR
ARG NGINX_PHP_BACKEND_NAME
ARG NGINX_PHP_BACKEND_PORT
ARG UID
ARG SYMFONY_ENTRYPOINT

RUN usermod -u $UID www-data

RUN apt-get update && apt-get install -y gettext

# nginx.conf
COPY nginx.conf /etc/nginx/nginx.conf

# vhost.conf
COPY vhost.conf.template /etc/nginx/conf.d/vhost.conf.template
RUN envsubst '$SYMFONY_ENTRYPOINT $NGINX_PUBLIC_DIR $NGINX_PHP_BACKEND_NAME $NGINX_PHP_BACKEND_PORT' < /etc/nginx/conf.d/vhost.conf.template > /etc/nginx/conf.d/default.conf
